package net.kozibrodka.planes.properties;

import net.kozibrodka.planes.events.mod_Planes;
import net.kozibrodka.planes.model.ModelPlane;
import net.kozibrodka.planes.model.ModelPlaneNew;
import net.minecraft.item.ItemStack;
import net.modificationstation.stationapi.api.template.item.TemplateItem;
/// Plane Propeties (change name later propably...)
public class Machine_properties {
    public float maxPropSpeed;
    public float takeOffSpeed;
    public int barrelX;
    public int barrelY;
    public int barrelZ;
    public int bombXOffset;
    public int bombYOffset;
    public int bombZOffset;
    public int propellerX;
    public int propellerY;
    public int propellerZ;
    public int numPassengers;
    public int passengerL;
    public boolean hasGuns;
    public String name;
    public String shortName;
    public String texture;
    public int planeHealth;
    public int planeShootDelay;
    public int planeBombDelay;
    public double lookDownModifier;
    public double lookUpModifier;
    public double turnLeftModifier;
    public double turnRightModifier;
    public double acceleration;
    public double decceleration;
    public int maxHeight;
    public String startSound;
    public int startSoundLength;
    public String propSound;
    public int propSoundLength;
    public String shootSound;
    public int numCargoSlots;
    public int numBulletSlots;
    public int numBombSlots;
    public int numRocketSlots;
    public boolean hasBombs;
    public String bombSound;
    public double playerYOffset;
    public double playerXOffset;
    public double playerZOffset;
    public int seatsX[];
    public int seatsY[];
    public int seatsZ[];
    public int planeFuelAdd;
    public boolean sloped;
    public int slopedPitch;
    public float planeWidth;
    public float planeHeight;
    public float standingOko;
    public boolean oldClassic;

    public int dyeColor;
    public ItemStack item_tail;
    public ItemStack item_cockpit;
    public ItemStack item_propeller;
    public ItemStack item_wings;
    public ItemStack item_guns;
    public ItemStack item_bay;
    public String itemlist1;
    public String itemlist2;
    public String itemlist3;
    public ModelPlane model;
    public ModelPlaneNew modelNew;
    public TemplateItem przedmiot;
}
