package net.kozibrodka.planes.properties;

import net.kozibrodka.planes.model.ModelPlane;
import net.minecraft.item.ItemInstance;
import net.modificationstation.stationapi.api.template.item.TemplateItemBase;

import java.util.ArrayList;
import java.util.List;

public class PlaneType {

    public PlaneType(Machine_properties klasa) {

        name = klasa.name;
        shortName = klasa.shortName;
        przedmiot = klasa.przedmiot;
        model = klasa.model;
        maxPropSpeed = klasa.maxPropSpeed;
        takeOffSpeed = klasa.takeOffSpeed;
        barrelX = klasa.barrelX;
        barrelY = klasa.barrelY;
        barrelZ = klasa.barrelZ;
        bombXOffset = klasa.bombXOffset;
        bombYOffset = klasa.bombYOffset;
        bombZOffset = klasa.bombZOffset;
        propellerX = klasa.propellerX;
        propellerY = klasa.propellerY;
        propellerZ = klasa.propellerZ;
        hasGuns = klasa.hasGuns;
        hasBombs = klasa.hasBombs;
        planeShootDelay = klasa.planeShootDelay;
        planeBombDelay = klasa.planeBombDelay;
        numCargoSlots = klasa.numCargoSlots;
        numBulletSlots = klasa.numBulletSlots;
        numBombSlots = klasa.numBombSlots;
        numRocketSlots = klasa.numRocketSlots;
        planeHealth = klasa.planeHealth;
        turnLeftModifier = klasa.turnLeftModifier;
        turnRightModifier = klasa.turnRightModifier;
        lookUpModifier = klasa.lookUpModifier;
        lookDownModifier = klasa.lookDownModifier;
        acceleration = klasa.acceleration;
        decceleration = klasa.decceleration;
        maxHeight = klasa.maxHeight;
        startSound = klasa.startSound;
        startSoundLength = klasa.startSoundLength;
        propSound = klasa.propSound;
        propSoundLength = klasa.propSoundLength;
        shootSound = klasa.shootSound;
        bombSound = klasa.bombSound;
        playerYOffset = klasa.playerYOffset;
        numPassengers = klasa.numPassengers;
        seatsX = klasa.seatsX;
        seatsY = klasa.seatsY;
        seatsZ = klasa.seatsZ;
        passengerL = klasa.passengerL;
        if (klasa.passengerL > 0) {
            seatsX[passengerL] = klasa.seatsX[klasa.passengerL];
            seatsY[passengerL] = klasa.seatsX[klasa.passengerL];
            seatsZ[passengerL] = klasa.seatsX[klasa.passengerL];
        }
        item_propeller = klasa.item_propeller;
        item_cockpit = klasa.item_cockpit;
        item_wings = klasa.item_wings;
        item_guns = klasa.item_guns;
        item_bay = klasa.item_bay;
        item_tail = klasa.item_tail;
        dyeColor = klasa.dyeColor;
        itemlist1 = klasa.itemlist1;
        itemlist2 = klasa.itemlist2;
        itemlist3 = klasa.itemlist3;
        planeFuelAdd = klasa.planeFuelAdd;
        types.add(this);
    }

    public float maxPropSpeed;
    public float takeOffSpeed;
    public int barrelX;
    public int barrelY;
    public int barrelZ;
    public int bombXOffset;
    public int bombYOffset;
    public int bombZOffset;
    public int propellerX;
    public int propellerY;
    public int propellerZ;
    public int numPassengers;
    public int passengerL;
    public boolean hasGuns;
    public String name;
    public String shortName;
    public int planeHealth;
    public int planeShootDelay;
    public int planeBombDelay;
    public double lookDownModifier;
    public double lookUpModifier;
    public double turnLeftModifier;
    public double turnRightModifier;
    public double acceleration;
    public double decceleration;
    public int maxHeight;
    public String startSound;
    public int startSoundLength;
    public String propSound;
    public int propSoundLength;
    public String shootSound;
    public int numCargoSlots;
    public int numBulletSlots;
    public int numBombSlots;
    public int numRocketSlots;
    public boolean hasBombs;
    public String bombSound;
    public double playerYOffset;
    public int seatsX[];
    public int seatsY[];
    public int seatsZ[];
    public ItemInstance item_bay;
    public int dyeColor;
    public ItemInstance item_tail;
    public ItemInstance item_cockpit;
    public ItemInstance item_propeller;
    public ItemInstance item_wings;
    public ItemInstance item_guns;
    public String itemlist1;
    public String itemlist2;
    public String itemlist3;
    public ModelPlane model;
    public boolean nowoczesny;
    public static List types = new ArrayList();
    public TemplateItemBase przedmiot;
    public int planeFuelAdd;
}